name: Check Docker Compose Version

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-docker-compose-version:
    runs-on: ubuntu-latest

    steps:
      - name: Verify Docker Compose version
        run: docker compose version


      - name: Print Docker Version
        run: docker version

